const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const db=window.supabaseClient;
let session,user,store,products=[],orders=[],categories=[],selectedOrder=null,editingProductId=null;
const labels={novo:'Novo',preparo:'Em preparo',pronto:'Pronto',entregue:'Entregue',cancelado:'Cancelado'};

async function init(){
  const {data:{session:s}}=await db.auth.getSession();
  if(!s){location.replace('auth.html');return}
  session=s;user=s.user;
  const {data:est,error}=await db.from('estabelecimentos').select('*').eq('usuario_id',user.id).single();
  if(error||!est){alert('Não foi possível carregar o estabelecimento.');return}
  store=est;
  await loadData();
  bindNavigation();bindModals();bindActions();setupAccount();setupLabels();render();
}

async function loadData(){
  const [p,c,o]=await Promise.all([
    db.from('produtos').select('*,categorias(nome)').eq('estabelecimento_id',store.id).order('created_at',{ascending:false}),
    db.from('categorias').select('*').eq('estabelecimento_id',store.id).order('ordem'),
    db.from('pedidos').select('*,clientes(nome,telefone),itens_pedido(*)').eq('estabelecimento_id',store.id).order('created_at',{ascending:false})
  ]);
  products=(p.data||[]).map(x=>({id:x.id,name:x.nome,category:x.categorias?.nome||'Sem categoria',price:Number(x.preco),description:x.descricao||'',extras:[],active:x.ativo}));
  categories=c.data||[];
  orders=(o.data||[]).map(x=>({id:x.id,customer:x.clientes?.nome||'Cliente',phone:x.clientes?.telefone||'',address:x.tipo==='retirada'?'Retirada no balcão':formatAddress(x.endereco_entrega),items:(x.itens_pedido||[]).map(i=>({name:i.nome_produto,qty:i.quantidade,price:Number(i.valor_unitario)})),total:Number(x.total),payment:x.forma_pagamento||'A definir',status:x.status,time:new Date(x.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),date:new Date(x.created_at).toLocaleDateString('pt-BR')}));
}
const formatAddress=a=>!a?'Não informado':typeof a==='string'?a:[a.logradouro,a.numero,a.bairro].filter(Boolean).join(', ');

function bindNavigation(){document.querySelectorAll('[data-page]').forEach(btn=>btn.onclick=()=>openPage(btn.dataset.page));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>openPage(btn.dataset.go))}
function openPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.getElementById('page-title').textContent=id[0].toUpperCase()+id.slice(1);window.scrollTo(0,0)}
function openModal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''}
function bindModals(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModals);document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()})}

function orderCard(o,compact=false){return `<article class="order-card" data-order="${o.id}"><div class="order-main"><b>#${o.id} • ${o.customer}</b><small>${o.items.map(i=>`${i.qty}x ${i.name}`).join(', ')||'Sem itens'} • ${o.time}</small></div><div><span class="status ${o.status}">${labels[o.status]||o.status}</span><b style="display:block;text-align:right;margin-top:7px">${money(o.total)}</b></div>${compact?'':`<button class="btn btn-secondary">Abrir pedido</button>`}</article>`}
function render(){const activeOrders=orders.filter(o=>o.status!=='cancelado'),revenue=activeOrders.reduce((s,o)=>s+o.total,0);document.getElementById('metric-orders').textContent=activeOrders.length;document.getElementById('metric-revenue').textContent=money(revenue);document.getElementById('metric-ticket').textContent=money(revenue/activeOrders.length||0);document.getElementById('metric-customers').textContent=new Set(activeOrders.map(o=>o.phone).filter(Boolean)).size;document.getElementById('summary-products').textContent=products.filter(p=>p.active).length;document.getElementById('summary-preparing').textContent=orders.filter(o=>o.status==='preparo').length;document.getElementById('recent-orders').innerHTML=orders.slice(0,4).map(o=>orderCard(o,true)).join('')||'<div class="empty-state">Nenhum pedido recebido.</div>';['novo','preparo','pronto','entregue'].forEach(s=>document.getElementById(`orders-${s}`).innerHTML=orders.filter(o=>o.status===s).map(o=>orderCard(o)).join('')||'<small style="color:var(--muted)">Nenhum pedido</small>');renderProducts();renderCustomers();renderFinance();document.querySelectorAll('[data-order]').forEach(el=>el.onclick=()=>openOrder(Number(el.dataset.order)))}
function renderProducts(){const q=(document.getElementById('product-search')?.value||'').toLowerCase(),cat=document.getElementById('category-filter')?.value||'';document.getElementById('product-list').innerHTML=products.filter(p=>(!cat||p.category===cat)&&p.name.toLowerCase().includes(q)).map(p=>`<article class="row-card"><div class="order-main"><b>${p.name}</b><small>${p.category} • ${p.description||'Sem descrição'}</small></div><div><b>${money(p.price)}</b><small style="display:block;color:${p.active?'#73d986':'#ff8d8d'}">${p.active?'Disponível':'Pausado'}</small></div><div class="inline-actions"><button class="btn btn-secondary" data-edit-product="${p.id}">Editar</button><button class="btn btn-secondary" data-toggle-product="${p.id}">${p.active?'Pausar':'Ativar'}</button><button class="btn btn-danger" data-delete-product="${p.id}">Excluir</button></div></article>`).join('')||'<div class="empty-state">Nenhum produto encontrado.</div>';document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(b.dataset.editProduct));document.querySelectorAll('[data-toggle-product]').forEach(b=>b.onclick=async()=>{const p=products.find(x=>x.id===b.dataset.toggleProduct);const {error}=await db.from('produtos').update({ativo:!p.active}).eq('id',p.id);if(error)return alert(error.message);p.active=!p.active;render()});document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=async()=>{const p=products.find(x=>x.id===b.dataset.deleteProduct);if(confirm(`Excluir ${p.name}?`)){const {error}=await db.from('produtos').delete().eq('id',p.id);if(error)return alert(error.message);products=products.filter(x=>x.id!==p.id);render()}})}
function renderCustomers(){const map={};orders.filter(o=>o.status!=='cancelado').forEach(o=>{const key=o.phone||o.customer;map[key]??={name:o.customer,phone:o.phone,count:0,total:0,last:o.time};map[key].count++;map[key].total+=o.total});document.getElementById('customer-table').innerHTML=Object.values(map).map(c=>`<tr><td><b>${c.name}</b></td><td>${c.phone||'-'}</td><td>${c.count}</td><td>${money(c.total)}</td><td>${c.last}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum cliente cadastrado.</td></tr>'}
function renderFinance(){const section=document.getElementById('financeiro'),valid=orders.filter(o=>o.status!=='cancelado'),revenue=valid.reduce((s,o)=>s+o.total,0);section.querySelectorAll('.metric strong')[0].textContent=money(revenue);section.querySelectorAll('.metric strong')[1].textContent=money(valid.filter(o=>o.status==='entregue').reduce((s,o)=>s+o.total,0));section.querySelectorAll('.metric strong')[2].textContent=money(valid.filter(o=>o.status!=='entregue').reduce((s,o)=>s+o.total,0));section.querySelectorAll('.metric strong')[3].textContent=money(valid.reduce((s,o)=>s+(o.address==='Retirada no balcão'?0:Number(store.taxa_entrega)||0),0))}

async function ensureCategory(name){let c=categories.find(x=>x.nome===name);if(c)return c.id;const {data,error}=await db.from('categorias').insert({estabelecimento_id:store.id,nome:name,ordem:categories.length}).select().single();if(error)throw error;categories.push(data);return data.id}
function editProduct(id){editingProductId=id;const p=products.find(x=>x.id===id),form=document.getElementById('product-form');form.elements.name.value=p.name;form.elements.category.value=p.category;form.elements.price.value=String(p.price).replace('.',',');form.elements.description.value=p.description||'';form.elements.extras.value='';document.querySelector('#product-modal h2').textContent='Editar produto';openModal('product-modal')}
function bindActions(){
  document.getElementById('new-product-btn').onclick=()=>{editingProductId=null;document.getElementById('product-form').reset();document.querySelector('#product-modal h2').textContent='Novo produto';openModal('product-modal')};
  document.getElementById('product-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const categoria_id=await ensureCategory(String(f.get('category')));const payload={estabelecimento_id:store.id,categoria_id,nome:String(f.get('name')).trim(),preco:Number(String(f.get('price')).replace(',','.')),descricao:String(f.get('description')||'')};if(editingProductId){const {error}=await db.from('produtos').update(payload).eq('id',editingProductId);if(error)throw error}else{const {error}=await db.from('produtos').insert({...payload,ativo:true});if(error)throw error}await loadData();closeModals();render()}catch(error){alert(error.message)}};
  document.getElementById('product-search').oninput=renderProducts;document.getElementById('category-filter').onchange=renderProducts;
  document.getElementById('advance-order').onclick=async()=>{const flow=['novo','preparo','pronto','entregue'],status=flow[Math.min(flow.indexOf(selectedOrder.status)+1,3)];const {error}=await db.from('pedidos').update({status,atualizado_em:new Date().toISOString()}).eq('id',selectedOrder.id);if(error)return alert(error.message);selectedOrder.status=status;closeModals();render()};
  document.getElementById('print-order').onclick=()=>window.print();
  document.getElementById('new-order-btn').onclick=()=>alert('O novo pedido será criado pelo fluxo da loja pública.');
}
function openOrder(id){selectedOrder=orders.find(o=>o.id===id);document.getElementById('order-modal-title').textContent=`Pedido #${id}`;document.getElementById('order-detail').innerHTML=`<div style="text-align:center"><h2>${store.nome.toUpperCase()}</h2><small>Pedido #${id} • ${selectedOrder.time}</small></div><hr><p><b>Cliente:</b> ${selectedOrder.customer}<br><b>Telefone:</b> ${selectedOrder.phone||'-'}<br><b>Entrega:</b> ${selectedOrder.address}</p><hr>${selectedOrder.items.map(i=>`<p>${i.qty}x ${i.name}<b style="float:right">${money(i.qty*i.price)}</b></p>`).join('')}<hr><h3>Total <span style="float:right">${money(selectedOrder.total)}</span></h3><p><b>Pagamento:</b> ${selectedOrder.payment}<br><b>Status:</b> ${labels[selectedOrder.status]}</p><div class="inline-actions"><button class="btn btn-danger" id="cancel-order">Cancelar pedido</button><button class="btn btn-danger" id="delete-order">Excluir registro</button></div>`;document.getElementById('advance-order').style.display=['entregue','cancelado'].includes(selectedOrder.status)?'none':'inline-flex';openModal('order-modal');document.getElementById('cancel-order').onclick=async()=>{if(confirm('Cancelar este pedido?')){const {error}=await db.from('pedidos').update({status:'cancelado'}).eq('id',id);if(error)return alert(error.message);selectedOrder.status='cancelado';closeModals();render()}};document.getElementById('delete-order').onclick=async()=>{if(confirm('Excluir permanentemente este pedido?')){const {error}=await db.from('pedidos').delete().eq('id',id);if(error)return alert(error.message);orders=orders.filter(o=>o.id!==id);closeModals();render()}}}

function setupAccount(){document.querySelector('#inicio h1').textContent=`Olá, ${user.user_metadata?.owner_name||user.email.split('@')[0]}`;const cfg=document.getElementById('configuracoes'),inputs=cfg.querySelectorAll('input,select,textarea');inputs[0].value=store.nome;inputs[1].value=store.telefone||'';inputs[2].value=store.categoria||'Hamburgueria';inputs[3].value=store.descricao||'';inputs[4].value=String(store.taxa_entrega||0).replace('.',',');inputs[5].value=String(store.pedido_minimo||0).replace('.',',');inputs[6].value=`fsdelivery.com.br/${store.slug}`;inputs[7].checked=store.aberto;cfg.insertAdjacentHTML('beforeend',`<div class="panel danger-zone" style="margin-top:18px"><div class="panel-head"><div><h2>Conta e segurança</h2><p style="color:var(--muted);margin:5px 0 0">Gerencie sua sessão e seus dados.</p></div></div><div class="inline-actions"><button class="btn btn-secondary" id="logout-btn">Sair da conta</button><button class="btn btn-danger" id="delete-account-btn">Excluir conta</button></div></div>`);document.getElementById('logout-btn').onclick=async()=>{await db.auth.signOut();location.replace('auth.html')};document.getElementById('delete-account-btn').onclick=async()=>{if(!confirm('Esta ação excluirá permanentemente a conta e todos os dados. Continuar?'))return;const {error}=await db.functions.invoke('delete-account',{body:{confirm:true}});if(error)return alert('Não foi possível excluir a conta.');await db.auth.signOut();location.replace('auth.html')};document.getElementById('save-settings').onclick=async()=>{const payload={nome:inputs[0].value,telefone:inputs[1].value,categoria:inputs[2].value,descricao:inputs[3].value,taxa_entrega:Number(inputs[4].value.replace(',','.'))||0,pedido_minimo:Number(inputs[5].value.replace(',','.'))||0,aberto:inputs[7].checked};const {data,error}=await db.from('estabelecimentos').update(payload).eq('id',store.id).select().single();if(error)return alert(error.message);store=data;setupLabels();alert('Configurações salvas.')}}
function setupLabels(){document.querySelector('.topbar-actions .btn').textContent=store.nome;document.querySelector('.topbar-actions .status').textContent=store.aberto?'Loja aberta':'Loja fechada';document.querySelector('.topbar-actions .status').className=`status ${store.aberto?'pronto':'cancelado'}`}
init();