const db=window.supabaseClient;
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const el=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

let store=null,config=null,products=[],tables=[],cart=[],current=null,qty=1,currentType='retirada',currentCategory='',canSell=true;

async function init(){
  try{
    const sessionResult=await db.auth.getSession(),session=sessionResult.data.session;if(!session){location.replace('auth.html');return}
    const storeResult=await db.from('estabelecimentos').select('*').eq('usuario_id',session.user.id).single();if(storeResult.error||!storeResult.data)throw storeResult.error||new Error('Estabelecimento não encontrado.');store=storeResult.data;
    const [productResult,tableResult,configResult,cashResult]=await Promise.all([
      db.from('produtos').select('id,nome,descricao,preco,imagem_url,destaque,categorias(nome)').eq('estabelecimento_id',store.id).eq('ativo',true).order('nome'),
      db.from('mesas').select('id,numero,nome,codigo_qr').eq('estabelecimento_id',store.id).eq('ativo',true).order('numero'),
      db.from('configuracoes_operacionais').select('*').eq('estabelecimento_id',store.id).maybeSingle(),
      db.from('caixas').select('id').eq('estabelecimento_id',store.id).eq('status','aberto').limit(1).maybeSingle()
    ]);
    if(productResult.error)throw productResult.error;if(tableResult.error)throw tableResult.error;
    products=(productResult.data||[]).map(product=>({id:product.id,name:product.nome,description:product.descricao||'',price:Number(product.preco),imageUrl:product.imagem_url||'',featured:Boolean(product.destaque),category:product.categorias?.nome||'Sem categoria'}));tables=tableResult.data||[];config=configResult.data||{};
    if(config.exige_abertura_caixa&&!cashResult.data){canSell=false;showWarning('Abra o caixa antes de criar novos pedidos.')}
    if(!store.aberto){canSell=false;showWarning('A loja está fechada. Abra o estabelecimento para liberar novos pedidos.')}
    bind();renderPayments();renderTables();renderCategories();renderProducts();renderCart();updateType();el('counter-status').textContent=`${store.nome} • ${canSell?'Operação disponível':'Operação bloqueada'}`;el('counter-submit').disabled=!canSell;
  }catch(error){console.error(error);el('counter-products').innerHTML=`<div class="empty-state">${escapeHtml(error.message||'Não foi possível carregar a operação.')}</div>`;el('counter-status').textContent='Erro ao carregar'}
}
function showWarning(message){const warning=el('counter-warning');warning.textContent=message;warning.hidden=false}
function bind(){
  el('counter-search').oninput=renderProducts;document.querySelectorAll('[data-counter-type]').forEach(button=>button.onclick=()=>{currentType=button.dataset.counterType;document.querySelectorAll('[data-counter-type]').forEach(item=>item.classList.toggle('active',item===button));updateType()});document.querySelectorAll('[data-close]').forEach(button=>button.onclick=closeModal);el('counter-product-modal').onclick=event=>{if(event.target===el('counter-product-modal'))closeModal()};el('counter-minus').onclick=()=>{qty=Math.max(1,qty-1);updateProductModal()};el('counter-plus').onclick=()=>{qty+=1;updateProductModal()};el('counter-add').onclick=addProduct;el('counter-submit').onclick=submit;el('counter-mobile-cart').onclick=()=>el('counter-order-panel').scrollIntoView({behavior:'smooth',block:'start'})
}
function renderPayments(){let values=Array.isArray(config?.formas_pagamento)?config.formas_pagamento:['PIX','Cartão','Dinheiro','Pagamento no caixa'];if(!values.length)values=['PIX','Cartão','Dinheiro'];el('counter-payment').innerHTML=values.map(value=>`<option>${escapeHtml(value)}</option>`).join('')}
function renderTables(){el('counter-table').innerHTML='<option value="">Selecione uma mesa</option>'+tables.map(table=>`<option value="${table.id}" data-token="${escapeHtml(table.codigo_qr||'')}">${escapeHtml(table.nome||`Mesa ${String(table.numero).padStart(2,'0')}`)}</option>`).join('')}
function renderCategories(){const categories=[...new Set(products.map(product=>product.category))];el('counter-category-tabs').innerHTML=[{value:'',label:'Todos'},...categories.map(category=>({value:category,label:category}))].map(item=>`<button class="${item.value===currentCategory?'active':''}" type="button" data-category="${escapeHtml(item.value)}">${escapeHtml(item.label)}</button>`).join('');el('counter-category-tabs').querySelectorAll('[data-category]').forEach(button=>button.onclick=()=>{currentCategory=button.dataset.category;renderCategories();renderProducts()})}
function renderProducts(){const term=el('counter-search').value.trim().toLowerCase(),filtered=products.filter(product=>(!currentCategory||product.category===currentCategory)&&(!term||`${product.name} ${product.description}`.toLowerCase().includes(term)));el('counter-products').innerHTML=filtered.length?filtered.map(product=>`<button class="counter-product" type="button" data-product="${product.id}"><div><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description||product.category)}</p><strong>${money(product.price)}</strong></div>${product.imageUrl?`<img src="${escapeHtml(product.imageUrl)}" alt="${escapeHtml(product.name)}" loading="lazy" onerror="this.remove()">`:''}</button>`).join(''):'<div class="empty-state">Nenhum produto encontrado.</div>';el('counter-products').querySelectorAll('[data-product]').forEach(button=>button.onclick=()=>openProduct(button.dataset.product))}
function openProduct(id){current=products.find(product=>String(product.id)===String(id));if(!current)return;qty=1;el('counter-item-note').value='';el('counter-product-title').textContent=current.name;el('counter-product-description').textContent=current.description||'Sem descrição.';updateProductModal();el('counter-product-modal').classList.add('open');document.body.style.overflow='hidden'}
function updateProductModal(){el('counter-qty').textContent=qty;el('counter-add').textContent=`Adicionar • ${money((current?.price||0)*qty)}`}
function closeModal(){el('counter-product-modal').classList.remove('open');document.body.style.overflow=''}
function addProduct(){if(!current)return;cart.push({cartId:crypto.randomUUID(),productId:current.id,name:current.name,price:current.price,qty,note:el('counter-item-note').value.trim()});closeModal();renderCart()}
function subtotal(){return cart.reduce((sum,item)=>sum+item.price*item.qty,0)}
function total(){const base=subtotal(),delivery=currentType==='entrega'?Number(store?.taxa_entrega||0):0,service=['mesa','local'].includes(currentType)?base*Number(config?.taxa_servico_percentual||0)/100:0;return base+delivery+service}
function renderCart(){el('counter-cart').innerHTML=cart.length?cart.map(item=>`<div class="row-card"><div class="order-main"><b>${item.qty}x ${escapeHtml(item.name)}</b><small>${escapeHtml(item.note||money(item.price))}</small></div><div><b>${money(item.qty*item.price)}</b><button class="link-button" data-remove="${item.cartId}" type="button">Remover</button></div></div>`).join(''):'<div class="empty-state">Nenhum item adicionado.</div>';el('counter-cart').querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{cart=cart.filter(item=>item.cartId!==button.dataset.remove);renderCart()});const count=cart.reduce((sum,item)=>sum+item.qty,0),value=total();el('counter-total').textContent=money(value);el('counter-mobile-count').textContent=`${count} ${count===1?'item':'itens'}`;el('counter-mobile-total').textContent=money(value);el('counter-mobile-cart').hidden=count===0}
function updateType(){el('counter-table-field').hidden=currentType!=='mesa';el('counter-address-field').hidden=currentType!=='entrega';el('counter-destination').textContent={retirada:'Retirada no balcão',local:'Consumo no local',mesa:'Atendimento vinculado à mesa',entrega:'Entrega ao cliente'}[currentType];renderCart()}
async function submit(){
  if(!canSell)return;if(!cart.length)return alert('Adicione ao menos um produto.');const name=el('counter-name').value.trim(),phone=el('counter-phone').value.replace(/\D/g,''),address=el('counter-address').value.trim(),tableId=el('counter-table').value;if(currentType==='mesa'&&!tableId)return alert('Selecione uma mesa.');if(currentType==='entrega'&&address.length<8)return alert('Informe o endereço completo.');if(['entrega','retirada'].includes(currentType)&&(name.length<2||phone.length<10))return alert('Informe nome e WhatsApp válidos.');const selectedTable=el('counter-table').selectedOptions[0],payload={tipo:currentType,mesa_id:currentType==='mesa'?tableId:null,mesa_token:currentType==='mesa'?selectedTable?.dataset.token:null,nome:name||'Atendimento local',telefone:phone||`balcao${Date.now()}`,endereco:address,pagamento:el('counter-payment').value,observacoes:el('counter-notes').value.trim(),itens:cart.map(item=>({produto_id:item.productId,quantidade:item.qty,observacoes:item.note}))};const button=el('counter-submit'),original=button.textContent;button.disabled=true;button.textContent='Criando pedido...';try{const result=await db.rpc('criar_pedido_garcom',{payload});if(result.error)throw result.error;alert(`Pedido #${result.data} criado com sucesso.`);location.replace('app.html#pedidos')}catch(error){alert(error.message||'Não foi possível criar o pedido.');button.disabled=false;button.textContent=original}}

init();
