(()=>{
'use strict';
const db=window.supabaseClient;
const params=new URLSearchParams(location.search);
const slug=String(params.get('loja')||'').trim();
const requestedPhone=String(params.get('telefone')||'');
let requestedOrder=String(params.get('pedido')||'');
const container=document.getElementById('customer-orders');
const form=document.getElementById('customer-lookup-form');
const modal=document.getElementById('customer-order-modal');
const phoneInput=document.getElementById('lookup-phone');
let orders=[],activeOrderCode='',loading=false;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const digits=v=>String(v||'').replace(/\D/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const phoneKey=`fsdelivery_customer_phone_${slug}`;
const tokenKey=phone=>`fsdelivery_customer_token_${slug}_${digits(phone)}`;

function realStatus(order){const status=String(order.status||'novo').toLowerCase(),delivery=String(order.status_entrega||'').toLowerCase();if(status==='rejeitado')return{step:-1,label:'Pedido não aprovado',tone:'error'};if(status==='cancelado')return{step:-1,label:'Pedido cancelado',tone:'error'};if(delivery==='entregue'||status==='entregue'||(status==='finalizado'&&delivery==='entregue'))return{step:5,label:'Pedido entregue',tone:'success'};if(['em_rota','saiu_entrega','em_entrega'].includes(delivery)||['saiu_entrega','em_entrega'].includes(status))return{step:4,label:'Saiu para entrega',tone:'info'};if(order.tipo==='entrega'&&(['pronto','aguardando_entregador'].includes(status)||['pronto','aguardando_entregador'].includes(delivery)))return{step:3,label:'Pronto — aguardando entregador',tone:'warning'};if(order.tipo!=='entrega'&&['pronto','aguardando_retirada'].includes(status))return{step:3,label:'Pronto para retirada',tone:'warning'};if(['preparo','em_preparo'].includes(status))return{step:2,label:'Em preparo',tone:'info'};if(['confirmado','aceito'].includes(status))return{step:1,label:'Pedido aprovado — aguardando preparo',tone:'success'};if(['novo','aguardando_aprovacao'].includes(status))return{step:0,label:'Aguardando aprovação',tone:'warning'};if(status==='finalizado')return{step:5,label:order.tipo==='entrega'?'Pedido finalizado':'Pedido concluído',tone:'success'};return{step:0,label:status.replaceAll('_',' '),tone:'warning'}}
function address(order){const a=order.endereco_entrega;if(order.tipo==='mesa')return'Pedido na mesa';if(order.tipo==='retirada')return'Retirada no estabelecimento';if(order.tipo==='local')return'Consumo no local';if(!a)return'Endereço não informado';if(typeof a==='string')return a;return a.texto||a.endereco||[a.logradouro,a.numero,a.complemento,a.bairro,a.cidade,a.estado].filter(Boolean).join(', ')||'Endereço não informado'}
function state(title,message){container.innerHTML=`<div class="empty-state"><h3>${esc(title)}</h3><p>${esc(message)}</p></div>`}

function render(){if(!orders.length){state('Nenhum pedido encontrado','Este dispositivo não possui pedidos disponíveis nos últimos 90 dias.');return}container.innerHTML=`<div class="customer-orders-head"><div><h2>Seus pedidos</h2><small>${orders.length} pedido(s) nos últimos 90 dias</small></div><button class="btn btn-secondary" id="refresh-customer-orders" type="button">Atualizar</button></div><div class="customer-order-grid">${orders.map(o=>{const st=realStatus(o);return`<article class="customer-order-card" data-order="${esc(o.codigo||o.id)}"><div class="customer-order-card-top"><div><div class="customer-order-code">Pedido #${esc(o.codigo||o.id)} • ${date(o.created_at)}</div><h3>${esc(st.label)}</h3></div><span class="customer-order-badge ${st.tone}">${esc(st.label)}</span></div><div class="customer-order-items">${(o.itens||[]).map(i=>`${Number(i.quantidade)||1}x ${esc(i.nome)}`).join(' • ')}</div><div class="customer-order-footer"><span>Toque para acompanhar</span><strong>${money(o.total)}</strong></div></article>`}).join('')}</div>`;document.getElementById('refresh-customer-orders').onclick=()=>lookup(phoneInput.value,{silent:true,preserve:true});container.querySelectorAll('[data-order]').forEach(card=>card.onclick=()=>openOrder(card.dataset.order))}
function openOrder(code){const order=orders.find(item=>String(item.codigo||item.id).toLowerCase()===String(code).toLowerCase());if(!order)return;activeOrderCode=String(order.codigo||order.id);const status=realStatus(order),labels=order.tipo==='entrega'?['Aguardando aprovação','Pedido aprovado','Em preparo','Aguardando entregador','Saiu para entrega','Pedido entregue']:['Aguardando aprovação','Pedido aprovado','Em preparo','Pronto','Concluído'];document.getElementById('customer-order-title').textContent=`Pedido #${activeOrderCode}`;document.getElementById('customer-order-detail').innerHTML=`<div class="customer-order-state ${status.tone}">${esc(status.label)}</div>${status.step<0?'':`<div class="customer-order-timeline">${labels.map((label,index)=>`<div class="customer-order-step ${index<=status.step?'done':''} ${index===status.step?'current':''}">${esc(label)}</div>`).join('')}</div>`}<div class="receipt"><p><b>Modalidade:</b> ${esc(({mesa:'Mesa',local:'Consumo local',retirada:'Retirada',entrega:'Entrega'})[order.tipo]||order.tipo)}</p><p><b>Destino:</b> ${esc(address(order))}</p><p><b>Pagamento:</b> ${esc(order.forma_pagamento||'Não informado')}</p>${(order.itens||[]).map(item=>`<div class="receipt-line"><span>${Number(item.quantidade)||1}x ${esc(item.nome)}${item.observacoes?`<small>${esc(item.observacoes)}</small>`:''}</span><b>${money(item.total)}</b></div>`).join('')}<div class="receipt-line"><span>Subtotal</span><b>${money(order.subtotal)}</b></div>${Number(order.taxa_entrega)>0?`<div class="receipt-line"><span>Taxa de entrega</span><b>${money(order.taxa_entrega)}</b></div>`:'<div class="receipt-line"><span>Entrega</span><b>Grátis</b></div>'}<div class="receipt-total"><span>Total</span><b>${money(order.total)}</b></div></div>`;modal.classList.add('open');document.body.style.overflow='hidden'}

async function lookup(phone,{silent=false,preserve=false}={}){
  if(loading)return;const normalized=digits(phone);if(!slug){state('Loja não informada','Abra o histórico pelo cardápio da loja.');return}if(normalized.length<10||normalized.length>13){state('WhatsApp inválido','Informe o mesmo WhatsApp utilizado no pedido.');return}
  const token=localStorage.getItem(tokenKey(normalized));
  if(!token){state('Dispositivo não autorizado','O histórico só pode ser aberto no dispositivo vinculado após a realização de um pedido.');return}
  loading=true;if(!silent)state('Consultando pedidos','Validando este dispositivo com segurança.');
  try{const{data,error}=await db.rpc('consultar_pedidos_cliente',{p_slug:slug,p_telefone:normalized,p_token:token});if(error)throw error;orders=Array.isArray(data)?data:[];localStorage.setItem(phoneKey,normalized);render();if(preserve&&activeOrderCode)openOrder(activeOrderCode);else if(requestedOrder){openOrder(requestedOrder);requestedOrder=''}}catch(error){console.error(error);orders=[];state('Acesso não autorizado','Este dispositivo não possui autorização válida. Faça um novo pedido para vinculá-lo novamente.')}finally{loading=false}
}

form.onsubmit=event=>{event.preventDefault();requestedOrder='';activeOrderCode='';lookup(phoneInput.value)};
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>{modal.classList.remove('open');document.body.style.overflow='';activeOrderCode=''});
if(slug){document.querySelectorAll('a[href^="loja"]').forEach(link=>link.href=`loja?loja=${encodeURIComponent(slug)}`);const saved=requestedPhone||localStorage.getItem(phoneKey)||'';if(saved){phoneInput.value=saved;lookup(saved)}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&phoneInput.value&&localStorage.getItem(tokenKey(phoneInput.value)))lookup(phoneInput.value,{silent:true,preserve:Boolean(activeOrderCode)})});
})();
