(()=>{
'use strict';
const db=window.supabaseClient;
const params=new URLSearchParams(location.search);
const slug=String(params.get('loja')||'').trim();
const requestedPhone=String(params.get('telefone')||'');
let requestedOrder=String(params.get('pedido')||'');
const container=document.getElementById('customer-orders');
const form=document.getElementById('customer-lookup-form');
const modal=document.getElementById('customer-order-modal');
const phoneInput=document.getElementById('lookup-phone');
let orders=[],activeOrderCode='',pollTimer=null,loading=false;
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const digits=v=>String(v||'').replace(/\D/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});

function realStatus(order){
  const status=String(order.status||'novo').toLowerCase();
  const delivery=String(order.status_entrega||'').toLowerCase();
  if(status==='rejeitado')return{step:-1,label:'Pedido não aprovado',tone:'error'};
  if(status==='cancelado')return{step:-1,label:'Pedido cancelado',tone:'error'};
  if(delivery==='entregue'||status==='entregue'||(status==='finalizado'&&delivery==='entregue'))return{step:5,label:'Pedido entregue',tone:'success'};
  if(['em_rota','saiu_entrega','em_entrega'].includes(delivery)||['saiu_entrega','em_entrega'].includes(status))return{step:4,label:'Saiu para entrega',tone:'info'};
  if(order.tipo==='entrega'&&(['pronto','aguardando_entregador'].includes(status)||['pronto','aguardando_entregador'].includes(delivery)))return{step:3,label:'Pronto — aguardando entregador',tone:'warning'};
  if(order.tipo!=='entrega'&&['pronto','aguardando_retirada'].includes(status))return{step:3,label:'Pronto para retirada',tone:'warning'};
  if(['preparo','em_preparo'].includes(status))return{step:2,label:'Em preparo',tone:'info'};
  if(['confirmado','aceito'].includes(status))return{step:1,label:'Pedido aprovado — aguardando preparo',tone:'success'};
  if(['novo','aguardando_aprovacao'].includes(status))return{step:0,label:'Aguardando aprovação',tone:'warning'};
  if(status==='finalizado')return{step:5,label:order.tipo==='entrega'?'Pedido finalizado':'Pedido concluído',tone:'success'};
  return{step:0,label:status.replaceAll('_',' '),tone:'warning'};
}

function address(order){const a=order.endereco_entrega;if(order.tipo==='mesa')return'Pedido na mesa';if(order.tipo==='retirada')return'Retirada no estabelecimento';if(order.tipo==='local')return'Consumo no local';if(!a)return'Endereço não informado';if(typeof a==='string')return a;return a.texto||a.endereco||[a.logradouro,a.numero,a.complemento,a.bairro,a.cidade,a.estado].filter(Boolean).join(', ')||'Endereço não informado'}

function styles(){if(document.getElementById('customer-orders-v2'))return;const s=document.createElement('style');s.id='customer-orders-v2';s.textContent=`
.customer-orders{padding-bottom:32px}.customer-orders-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:18px 0}.customer-orders-head h2{margin:0}.customer-order-grid{display:grid;gap:14px}.customer-order-card{display:block;padding:18px;border:1px solid rgba(90,55,30,.16);border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(58,34,20,.06);cursor:pointer}.customer-order-card:active{transform:scale(.995)}.customer-order-card-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.customer-order-code{font-size:13px;color:#806f61}.customer-order-card h3{margin:7px 0 0;font-size:19px}.customer-order-badge{flex:0 0 auto;padding:7px 10px;border-radius:999px;font-size:12px;font-weight:800;background:#fff4dd;color:#8a5a00}.customer-order-badge.success{background:#eaf7ed;color:#26743a}.customer-order-badge.info{background:#edf4ff;color:#275a9b}.customer-order-badge.error{background:#fff0f0;color:#b43c3c}.customer-order-items{margin:14px 0;color:#69584b;line-height:1.45}.customer-order-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;padding-top:14px;border-top:1px solid rgba(90,55,30,.1)}.customer-order-footer strong{font-size:19px}.customer-order-footer span{font-size:13px;color:#8a7869}.customer-order-state{padding:14px 16px;border-radius:12px;background:#edf4ff;color:#275a9b;font-weight:800;margin-bottom:14px}.customer-order-state.success{background:#eaf7ed;color:#26743a}.customer-order-state.error{background:#fff0f0;color:#b43c3c}.customer-order-state.warning{background:#fff4dd;color:#8a5a00}.customer-order-timeline{display:grid;gap:8px;margin:0 0 18px}.customer-order-step{position:relative;padding:9px 12px 9px 34px;border-radius:10px;background:#f6f1ec;color:#8d7b6d;font-size:13px;font-weight:700}.customer-order-step:before{content:'';position:absolute;left:12px;top:12px;width:10px;height:10px;border-radius:50%;background:#d7cbc1}.customer-order-step.done{background:#eef8ef;color:#2d743e}.customer-order-step.done:before{background:#3d9250}.customer-order-step.current{box-shadow:inset 0 0 0 2px rgba(61,146,80,.22)}@media(max-width:560px){.customer-orders-head{align-items:flex-start}.customer-order-card-top{display:grid}.customer-order-badge{justify-self:start}.customer-order-footer{align-items:flex-end}}
`;document.head.appendChild(s)}

function render(){styles();if(!orders.length){container.innerHTML='<div class="empty-state"><h3>Nenhum pedido encontrado</h3><p>Confira o WhatsApp informado.</p></div>';return}container.innerHTML=`<div class="customer-orders-head"><div><h2>Seus pedidos</h2><small>${orders.length} pedido(s) nos últimos 90 dias</small></div><button class="btn btn-secondary" id="refresh-customer-orders" type="button">Atualizar</button></div><div class="customer-order-grid">${orders.map(o=>{const st=realStatus(o);return`<article class="customer-order-card" data-order="${esc(o.codigo||o.id)}"><div class="customer-order-card-top"><div><div class="customer-order-code">Pedido #${esc(o.codigo||o.id)} • ${date(o.created_at)}</div><h3>${esc(st.label)}</h3></div><span class="customer-order-badge ${st.tone}">${esc(st.label)}</span></div><div class="customer-order-items">${(o.itens||[]).map(i=>`${Number(i.quantidade)||1}x ${esc(i.nome)}`).join(' • ')}</div><div class="customer-order-footer"><span>Toque para acompanhar</span><strong>${money(o.total)}</strong></div></article>`}).join('')}</div>`;document.getElementById('refresh-customer-orders').onclick=()=>lookup(phoneInput.value,{silent:true,preserve:true});container.querySelectorAll('[data-order]').forEach(c=>c.onclick=()=>openOrder(c.dataset.order))}

function openOrder(code){const o=orders.find(x=>String(x.codigo||x.id).toLowerCase()===String(code).toLowerCase());if(!o)return;activeOrderCode=String(o.codigo||o.id);const st=realStatus(o);const labels=o.tipo==='entrega'?['Aguardando aprovação','Pedido aprovado','Em preparo','Aguardando entregador','Saiu para entrega','Pedido entregue']:['Aguardando aprovação','Pedido aprovado','Em preparo','Pronto','Concluído'];document.getElementById('customer-order-title').textContent=`Pedido #${activeOrderCode}`;document.getElementById('customer-order-detail').innerHTML=`<div class="customer-order-state ${st.tone}">${esc(st.label)}</div>${st.step<0?'':`<div class="customer-order-timeline">${labels.map((l,i)=>`<div class="customer-order-step ${i<=st.step?'done':''} ${i===st.step?'current':''}">${esc(l)}</div>`).join('')}</div>`}<div class="receipt"><p><b>Modalidade:</b> ${esc(({mesa:'Mesa',local:'Consumo local',retirada:'Retirada',entrega:'Entrega'})[o.tipo]||o.tipo)}</p><p><b>Destino:</b> ${esc(address(o))}</p><p><b>Pagamento:</b> ${esc(o.forma_pagamento||'Não informado')}</p>${(o.itens||[]).map(i=>`<div class="receipt-line"><span>${Number(i.quantidade)||1}x ${esc(i.nome)}${i.observacoes?`<small>${esc(i.observacoes)}</small>`:''}</span><b>${money(i.total)}</b></div>`).join('')}<div class="receipt-line"><span>Subtotal</span><b>${money(o.subtotal)}</b></div>${Number(o.taxa_entrega)>0?`<div class="receipt-line"><span>Taxa de entrega</span><b>${money(o.taxa_entrega)}</b></div>`:'<div class="receipt-line"><span>Entrega</span><b>Grátis</b></div>'}<div class="receipt-total"><span>Total</span><b>${money(o.total)}</b></div></div>`;modal.classList.add('open');document.body.style.overflow='hidden'}

async function lookup(phone,{silent=false,preserve=false}={}){if(loading)return;const normalized=digits(phone);if(!slug){container.innerHTML='<div class="empty-state">Loja não informada.</div>';return}if(normalized.length<10||normalized.length>13){container.innerHTML='<div class="empty-state">Informe um WhatsApp válido.</div>';return}loading=true;if(!silent)container.innerHTML='<div class="empty-state">Consultando pedidos...</div>';try{const{data,error}=await db.rpc('consultar_pedidos_cliente',{p_slug:slug,p_telefone:normalized});if(error)throw error;orders=Array.isArray(data)?data:[];localStorage.setItem(`fsdelivery_customer_phone_${slug}`,normalized);render();if(preserve&&activeOrderCode)openOrder(activeOrderCode);else if(requestedOrder){openOrder(requestedOrder);requestedOrder=''}}catch(e){console.error(e);container.innerHTML='<div class="empty-state"><h3>Não foi possível consultar</h3><p>Tente novamente.</p></div>'}finally{loading=false}}

function startPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(document.visibilityState==='visible'&&phoneInput.value)lookup(phoneInput.value,{silent:true,preserve:Boolean(activeOrderCode)})},7000)}
form.onsubmit=e=>{e.preventDefault();requestedOrder='';activeOrderCode='';lookup(phoneInput.value)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{modal.classList.remove('open');document.body.style.overflow='';activeOrderCode=''});if(slug){document.querySelectorAll('a[href="loja.html"]').forEach(a=>a.href=`loja?loja=${encodeURIComponent(slug)}`);const saved=requestedPhone||localStorage.getItem(`fsdelivery_customer_phone_${slug}`)||'';if(saved){phoneInput.value=saved;lookup(saved)}startPolling()}
})();