const db=window.supabaseClient,Status=window.FSOrderStatus,money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0),el=id=>document.getElementById(id);
let store=null,orders=[],scope='local',selected=null,updating=false,newOrderIds=new Set();
const activeStatuses=['confirmado','preparo'];
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function nextStep(order){const status=Status.normalize(order.status);if(status==='confirmado')return{status:'preparo',label:'Iniciar preparo',loading:'Iniciando...'};if(status==='preparo')return{status:'pronto',label:'Marcar pronto',loading:'Finalizando...'};return null}
async function init(){const{data:{session}}=await db.auth.getSession();if(!session)return location.replace('auth.html');const result=await db.from('estabelecimentos').select('*').eq('usuario_id',session.user.id).single();if(result.error||!result.data)return alert('Não foi possível carregar o estabelecimento.');store=result.data;bind();await load();render();window.FSOperationalNotifications.start({role:'cozinha',storeId:store.id,owner:true});db.channel(`cozinha-${store.id}`).on('postgres_changes',{event:'*',schema:'public',table:'pedidos',filter:`estabelecimento_id=eq.${store.id}`},async payload=>{if(['INSERT','UPDATE'].includes(payload.eventType)&&['novo','confirmado'].includes(payload.new?.status))newOrderIds.add(String(payload.new.id));await load();render()}).subscribe()}
function bind(){document.querySelectorAll('[data-kitchen-scope]').forEach(button=>button.onclick=()=>{scope=button.dataset.kitchenScope;document.querySelectorAll('[data-kitchen-scope]').forEach(item=>{const active=item===button;item.classList.toggle('btn-primary',active);item.classList.toggle('btn-secondary',!active)});render()});document.querySelectorAll('[data-close]').forEach(button=>button.onclick=closeModal);el('kitchen-order-modal').onclick=event=>{if(event.target===el('kitchen-order-modal'))closeModal()};el('kitchen-complete').onclick=completeSelected}
async function load(){el('kitchen-status').textContent='Atualizando';const result=await db.from('pedidos').select('id,numero,codigo,status,tipo,total,observacoes,created_at,mesa_id,clientes(nome,telefone),mesas(numero,nome),itens_pedido(quantidade,nome_produto,observacoes,total)').eq('estabelecimento_id',store.id).order('numero',{ascending:true,nullsFirst:false}).order('created_at',{ascending:true});if(result.error){el('kitchen-orders').innerHTML=`<div class="empty-state">Erro ao carregar pedidos: ${escapeHtml(result.error.message)}</div>`;orders=[];el('kitchen-status').textContent='Erro';return}orders=(result.data||[]).map(order=>({...order,status:Status.normalize(order.status)}));el('kitchen-status').textContent='Ao vivo'}
function filtered(){const localTypes=['mesa','local'];return orders.filter(order=>activeStatuses.includes(order.status)&&(scope==='local'?localTypes.includes(order.tipo):!localTypes.includes(order.tipo)))}
function orderNumber(order){return order.numero?`#${String(order.numero).padStart(4,'0')}`:`#${order.codigo||order.id}`}
function reference(order){if(order.tipo==='mesa')return order.mesas?.nome||`Mesa ${order.mesas?.numero||''}`;return order.clientes?.nome||({entrega:'Entrega',retirada:'Retirada',local:'Consumo local'})[order.tipo]||'Pedido'}
function render(){const list=filtered();el('kitchen-list-title').textContent=scope==='local'?'Pedidos locais':'Pedidos on-line';el('kitchen-queued').textContent=orders.filter(order=>order.status==='confirmado').length;el('kitchen-preparing').textContent=orders.filter(order=>order.status==='preparo').length;const today=new Date().toDateString();el('kitchen-ready').textContent=orders.filter(order=>order.status==='pronto'&&new Date(order.created_at).toDateString()===today).length;el('kitchen-orders').innerHTML=list.length?list.map(order=>{const step=nextStep(order),fresh=newOrderIds.has(String(order.id));return`<article class="kitchen-card ${fresh?'is-new':''}" data-kitchen-order="${escapeHtml(order.id)}"><div class="kitchen-card-head"><span class="status ${Status.css(order.status)}">${escapeHtml(Status.label(order.status,order.tipo))}</span><b>${escapeHtml(orderNumber(order))}</b></div><h3>${escapeHtml(reference(order))}</h3><div class="kitchen-items">${(order.itens_pedido||[]).map(item=>`<p><b>${Number(item.quantidade)}x</b> ${escapeHtml(item.nome_produto)}${item.observacoes?`<small>${escapeHtml(item.observacoes)}</small>`:''}</p>`).join('')||'<p>Sem itens</p>'}</div>${order.observacoes?`<div class="kitchen-note">${escapeHtml(order.observacoes)}</div>`:''}<div class="kitchen-card-foot"><small>${new Date(order.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small><strong>${money(order.total)}</strong></div>${step?`<button class="btn btn-primary btn-block" data-complete-order="${escapeHtml(order.id)}">${step.label}</button>`:''}</article>`}).join(''):`<div class="empty-state">Nenhum pedido ${scope==='local'?'local':'on-line'} aguardando a cozinha.</div>`;document.querySelectorAll('[data-kitchen-order]').forEach(card=>card.onclick=event=>{if(!event.target.closest('[data-complete-order]'))openOrder(card.dataset.kitchenOrder)});document.querySelectorAll('[data-complete-order]').forEach(button=>button.onclick=()=>advanceOrder(button.dataset.completeOrder,button));setTimeout(()=>{newOrderIds.clear()},3000)}
function openOrder(id){selected=orders.find(order=>String(order.id)===String(id));if(!selected)return;const step=nextStep(selected);el('kitchen-order-title').textContent=`Pedido ${orderNumber(selected)}`;el('kitchen-order-detail').innerHTML=`<div class="row-card"><div><b>${escapeHtml(reference(selected))}</b><small>${escapeHtml(Status.typeLabel(selected.tipo))}</small></div><span class="status ${Status.css(selected.status)}">${escapeHtml(Status.label(selected.status,selected.tipo))}</span></div><div class="product-list">${(selected.itens_pedido||[]).map(item=>`<div class="row-card"><div><b>${Number(item.quantidade)}x ${escapeHtml(item.nome_produto)}</b><small>${escapeHtml(item.observacoes||'Sem observações')}</small></div><b>${money(item.total)}</b></div>`).join('')}</div>${selected.observacoes?`<div class="kitchen-note">${escapeHtml(selected.observacoes)}</div>`:''}`;el('kitchen-complete').textContent=step?.label||'Sem ação disponível';el('kitchen-complete').disabled=!step;el('kitchen-order-modal').classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){el('kitchen-order-modal').classList.remove('open');document.body.style.overflow='';selected=null}
async function completeSelected(){if(selected)await advanceOrder(selected.id,el('kitchen-complete'))}
async function advanceOrder(id,button){if(updating)return;const order=orders.find(item=>String(item.id)===String(id)),step=order&&nextStep(order);if(!step)return alert('Este pedido não está em uma etapa válida da cozinha.');if(!confirm(step.status==='preparo'?'Iniciar o preparo deste pedido?':'Confirmar que este pedido está pronto?'))return;updating=true;button.disabled=true;const previous=button.textContent;button.textContent=step.loading;const result=await db.rpc('atualizar_status_pedido_operacional',{p_pedido_id:Number(id),p_novo_status:step.status,p_origem:'cozinha'});updating=false;button.disabled=false;button.textContent=previous;if(result.error)return alert(result.error.message||'Não foi possível atualizar o pedido.');closeModal();await load();render()}
init();
