(()=>{
 const S={aliases:{novo:'confirmado',entregue:'finalizado',concluido:'finalizado','concluído':'finalizado',em_preparo:'preparo',saiu_para_entrega:'saiu_entrega'},labels:{aguardando_aprovacao:'Aguardando aprovação',confirmado:'Na fila da cozinha',preparo:'Em preparo',pronto:'Pronto',saiu_entrega:'Em rota',finalizado:'Finalizado',cancelado:'Cancelado'},active:['aguardando_aprovacao','confirmado','preparo','pronto','saiu_entrega'],filters:[['ativos','Todos ativos'],['aguardando_aprovacao','Aguardando'],['confirmado','Na cozinha'],['preparo','Em preparo'],['pronto','Prontos'],['saiu_entrega','Em rota'],['finalizado','Finalizados'],['cancelado','Cancelados']]};
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const norm=v=>{const x=String(v||'confirmado').toLowerCase().trim().replace(/[\s-]+/g,'_');return S.aliases[x]||x};
 const type=t=>({mesa:'Mesa',local:'Consumo local',retirada:'Retirada',entrega:'Entrega'})[t]||t;
 const address=a=>!a?'Não informado':typeof a==='string'?a:[a.endereco||a.logradouro,a.numero,a.complemento,a.bairro,a.cidade,a.referencia].filter(Boolean).join(', ')||'Não informado';
 const elapsed=d=>{const m=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));return m<1?'Agora':m<60?`${m} min`:`${Math.floor(m/60)}h ${m%60}min`};
 const label=o=>o.status==='pronto'?(o.type==='entrega'?'Pronto para entrega':o.type==='retirada'?'Pronto para retirada':'Pronto para servir'):(S.labels[o.status]||o.status);
 const css=s=>({aguardando_aprovacao:'novo',confirmado:'novo',saiu_entrega:'pronto',finalizado:'entregue'})[s]||s;
 const table=r=>r?.nome||(r?.numero?`Mesa ${String(r.numero).padStart(2,'0')}`:'');
 const map=r=>{const createdAt=new Date(r.created_at),t=r.tipo||'entrega',mesa=table(r.mesas),customer=r.clientes?.nome||r.cliente_nome||mesa||'Cliente';return{id:Number(r.id),code:r.codigo||String(r.numero||r.id),customer,phone:r.clientes?.telefone||r.cliente_telefone||'',type:t,table:mesa,address:t==='mesa'?(mesa||'Mesa não identificada'):t==='local'?'Consumo local':t==='retirada'?'Retirada no balcão':address(r.endereco_entrega),items:(r.itens_pedido||[]).map(i=>({name:i.nome_produto,qty:Number(i.quantidade),price:Number(i.valor_unitario),note:i.observacoes||''})),total:Number(r.total),payment:r.forma_pagamento||'A definir',status:norm(r.status),createdAt,time:createdAt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),date:createdAt.toLocaleDateString('pt-BR')}};
 const action=o=>o.status==='aguardando_aprovacao'?{status:'confirmado',text:'Aprovar pedido',origin:'caixa',approve:true}:o.status==='confirmado'?{status:'preparo',text:'Iniciar preparo',origin:'admin'}:o.status==='preparo'?{status:'pronto',text:'Marcar como pronto',origin:'admin'}:o.status==='pronto'&&['mesa','local'].includes(o.type)?{status:'finalizado',text:'Marcar como servido',origin:'admin'}:o.status==='pronto'&&o.type==='retirada'?{status:'finalizado',text:'Confirmar retirada',origin:'caixa'}:null;
 function setup(){const page=document.getElementById('pedidos');if(!page)return;page.innerHTML=`<div class="page-head orders-page-head"><div><h1>Pedidos</h1><p>Acompanhe cada pedido desde a criação até a conclusão.</p></div><button class="btn btn-primary" id="new-order-btn" type="button">+ Novo pedido</button></div><div class="order-status-tabs">${S.filters.map(([v,l],i)=>`<button type="button" class="${i?'':'active'}" data-order-filter="${v}">${l} <b id="count-${v}">0</b></button>`).join('')}</div><div class="orders-active-list" id="orders-active-list"></div>`;document.getElementById('new-order-btn').onclick=()=>location.href='balcao.html';document.querySelectorAll('[data-order-filter]').forEach(b=>b.onclick=()=>{activeOrderFilter=b.dataset.orderFilter;renderOrders()});const home=document.querySelector('#inicio .page-head .btn-primary');if(home){home.removeAttribute('onclick');home.onclick=()=>location.href='balcao.html'}}
 function card(o,compact=false){const count=o.items.reduce((n,i)=>n+i.qty,0),a=action(o);return`<article class="order-card operational-order-card status-${css(o.status)}" data-order="${o.id}"><div class="operational-order-top"><div><div class="operational-order-number">#${esc(o.code)} <span class="status ${css(o.status)}">${esc(label(o))}</span></div><b>${esc(o.customer)}</b><small>${esc(o.phone||o.address)}</small></div><div class="operational-order-time"><b>${esc(o.time)}</b><small>${esc(elapsed(o.createdAt))}</small></div></div><div class="operational-order-body"><div><b>${esc(type(o.type))}${o.table?` • ${esc(o.table)}`:''}</b><small>${esc(o.address)}</small></div><div class="operational-order-total"><b>${money(o.total)}</b><small>${esc(o.payment)}</small></div></div><div class="operational-order-footer"><span>${count} ${count===1?'item':'itens'}</span>${compact?'':`<div class="inline-actions"><button class="btn btn-secondary" data-open-order="${o.id}">Ver detalhes</button>${a?`<button class="btn btn-primary" data-op-action="${o.id}">${esc(a.text)}</button>`:''}</div>`}</div></article>`}
 window.orderCard=card;
 window.renderOrders=()=>{S.filters.forEach(([f])=>{const x=document.getElementById(`count-${f}`);if(x)x.textContent=orders.filter(o=>f==='ativos'?S.active.includes(o.status):o.status===f).length});document.querySelectorAll('[data-order-filter]').forEach(b=>b.classList.toggle('active',b.dataset.orderFilter===activeOrderFilter));const list=orders.filter(o=>activeOrderFilter==='ativos'?S.active.includes(o.status):o.status===activeOrderFilter),root=document.getElementById('orders-active-list');if(!root)return;root.innerHTML=list.length?list.map(o=>card(o)).join(''):`<div class="empty-state orders-empty">Nenhum pedido em ${esc(activeOrderFilter==='ativos'?'andamento':S.labels[activeOrderFilter]?.toLowerCase()||activeOrderFilter)}.</div>`;root.querySelectorAll('[data-order]').forEach(x=>x.onclick=e=>{if(!e.target.closest('button'))openOrder(Number(x.dataset.order))});root.querySelectorAll('[data-open-order]').forEach(x=>x.onclick=()=>openOrder(Number(x.dataset.openOrder)));root.querySelectorAll('[data-op-action]').forEach(x=>x.onclick=()=>advanceOrder(Number(x.dataset.opAction),x))};
 window.renderFinance=()=>{const section=document.getElementById('financeiro'),valid=orders.filter(o=>o.status!=='cancelado'),revenue=valid.reduce((n,o)=>n+o.total,0),received=valid.filter(o=>o.status==='finalizado').reduce((n,o)=>n+o.total,0);if(!section)return;const m=section.querySelectorAll('.metric strong');if(m[0])m[0].textContent=money(revenue);if(m[1])m[1].textContent=money(received);if(m[2])m[2].textContent=money(revenue-received);if(m[3])m[3].textContent=money(valid.filter(o=>o.type==='entrega').reduce((n)=>n+Number(store.taxa_entrega||0),0))};
 window.advanceOrder=async(id,button)=>{const o=orders.find(x=>x.id===id),a=o&&action(o);if(!a)return;const original=button?.textContent;if(button){button.disabled=true;button.textContent='Atualizando...'}try{const r=a.approve?await db.rpc('aprovar_pedido_caixa',{p_pedido_id:id}):await db.rpc('atualizar_status_pedido_operacional',{p_pedido_id:id,p_novo_status:a.status,p_origem:a.origin});if(r.error)throw r.error;await refresh()}catch(e){alert(e.message||'Não foi possível atualizar o pedido.')}finally{if(button){button.disabled=false;button.textContent=original}}};
 window.openOrder=async id=>{selectedOrder=orders.find(o=>o.id===id);if(!selectedOrder)return;const o=selectedOrder,a=action(o),title=document.getElementById('order-modal-title'),detail=document.getElementById('order-detail'),advance=document.getElementById('advance-order');title.textContent=`Pedido #${o.code}`;detail.innerHTML=`<p><b>Cliente:</b> ${esc(o.customer)}<br><b>Telefone:</b> ${esc(o.phone||'-')}<br><b>Atendimento:</b> ${esc(type(o.type))}${o.table?` • ${esc(o.table)}`:''}<br><b>Status:</b> ${esc(label(o))}</p><hr>${o.items.map(i=>`<p>${i.qty}x ${esc(i.name)}<b style="float:right">${money(i.qty*i.price)}</b>${i.note?`<small style="display:block">${esc(i.note)}</small>`:''}</p>`).join('')}<hr><h3>Total <span style="float:right">${money(o.total)}</span></h3><div class="panel" style="padding:14px;margin-top:14px"><b>Linha do tempo</b><div id="order-timeline" style="display:grid;gap:8px;margin-top:10px"><small>Carregando...</small></div></div>${['finalizado','cancelado'].includes(o.status)?'':`<div class="inline-actions" style="margin-top:14px"><button class="btn btn-danger" id="cancel-order">Cancelar pedido</button></div>`}`;advance.style.display=a?'inline-flex':'none';advance.textContent=a?.text||'';advance.onclick=()=>advanceOrder(o.id,advance);openModal('order-modal');document.getElementById('cancel-order')?.addEventListener('click',async()=>{if(!confirm('Cancelar este pedido?'))return;const r=await db.rpc('atualizar_status_pedido_operacional',{p_pedido_id:o.id,p_novo_status:'cancelado',p_origem:'admin'});if(r.error)return alert(r.error.message);closeModals();await refresh()});const ev=await db.from('pedido_eventos').select('status_novo,origem,created_at').eq('pedido_id',o.id).order('created_at');const tl=document.getElementById('order-timeline');if(tl)tl.innerHTML=ev.error?'<small>Histórico indisponível.</small>':(ev.data||[]).map(x=>`<div class="row-card" style="padding:9px"><div><b>${esc(S.labels[norm(x.status_novo)]||x.status_novo)}</b><small>${esc(x.origem||'sistema')}</small></div><small>${new Date(x.created_at).toLocaleString('pt-BR')}</small></div>`).join('')};
 async function refresh(){const r=await db.from('pedidos').select('*,clientes(nome,telefone),mesas(numero,nome),itens_pedido(*)').eq('estabelecimento_id',store.id).order('created_at',{ascending:false});if(r.error){document.getElementById('orders-active-list').innerHTML=`<div class="empty-state">Erro ao carregar pedidos: ${esc(r.error.message)}</div>`;return}orders=(r.data||[]).map(map);renderOrders();const recent=document.getElementById('recent-orders');if(recent)recent.innerHTML=orders.slice(0,4).map(o=>card(o,true)).join('')||'<div class="empty-state">Nenhum pedido recebido.</div>';document.getElementById('metric-orders').textContent=orders.filter(o=>o.status!=='cancelado').length;document.getElementById('summary-preparing').textContent=orders.filter(o=>o.status==='preparo').length;renderFinance()}
 async function start(){if(typeof db==='undefined'||typeof store==='undefined'||!store?.id)return setTimeout(start,250);Object.assign(labels,S.labels);activeOrderFilter='ativos';if(ordersChannel)db.removeChannel(ordersChannel);setup();await refresh();ordersChannel=db.channel(`operational-orders-${store.id}`).on('postgres_changes',{event:'*',schema:'public',table:'pedidos',filter:`estabelecimento_id=eq.${store.id}`},refresh).subscribe()}
 start();
})();
