-- Adicionais configuráveis por produto e validação dos valores no banco.
alter table public.itens_pedido add column if not exists ordem bigint generated by default as identity;

create or replace function public.aplicar_adicionais_pedido(p_estabelecimento uuid, p_codigo text, p_payload jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare
  v_item jsonb;
  v_produto uuid;
  v_item_id uuid;
  v_adicionais jsonb;
  v_ids uuid[];
  v_id uuid;
  v_nome text;
  v_preco numeric;
  v_base numeric;
  v_total_item numeric;
  v_processados uuid[] := '{}';
  v_pedido public.pedidos%rowtype;
  v_subtotal numeric := 0;
  v_taxa_servico numeric := 0;
  v_desconto numeric := 0;
  v_cfg public.configuracoes_operacionais%rowtype;
  v_coupon public.cupons%rowtype;
begin
  select * into v_pedido from public.pedidos where estabelecimento_id=p_estabelecimento and codigo=p_codigo for update;
  if not found then raise exception 'Pedido não localizado para aplicar adicionais'; end if;
  for v_item in select value from jsonb_array_elements(coalesce(p_payload->'itens','[]'::jsonb)) loop
    begin
      v_produto := (v_item->>'produto_id')::uuid;
    exception when others then raise exception 'Produto inválido'; end;
    select id,valor_unitario into v_item_id,v_base
      from public.itens_pedido
      where pedido_id=v_pedido.id and produto_id=v_produto and not (id=any(v_processados))
      order by ordem,id limit 1 for update;
    if v_item_id is null then raise exception 'Item do pedido não confere'; end if;
    v_processados := array_append(v_processados,v_item_id);
    v_ids := '{}';
    v_adicionais := coalesce(v_item->'adicionais','[]'::jsonb);
    if jsonb_typeof(v_adicionais)<>'array' then raise exception 'Adicionais inválidos'; end if;
    for v_id in select (value #>> '{}')::uuid from jsonb_array_elements(v_adicionais) loop
      if v_id=any(v_ids) then raise exception 'Adicional duplicado'; end if;
      v_ids := array_append(v_ids,v_id);
    end loop;
    if cardinality(v_ids)>0 and (
      select count(*) from unnest(v_ids) selected(id)
      join public.adicionais a on a.id=selected.id and a.ativo=true
      join public.grupos_adicionais g on g.id=a.grupo_id and g.produto_id=v_produto
    )<>cardinality(v_ids) then raise exception 'Adicional inválido ou indisponível'; end if;
    if exists(
      select 1 from public.grupos_adicionais g
      where g.produto_id=v_produto and g.obrigatorio=true
        and (select count(*) from unnest(v_ids) selected(id) join public.adicionais a on a.id=selected.id where a.grupo_id=g.id)<g.minimo
    ) then raise exception 'Selecione os adicionais obrigatórios'; end if;
    if exists(
      select 1 from public.grupos_adicionais g
      where g.produto_id=v_produto
        and (select count(*) from unnest(v_ids) selected(id) join public.adicionais a on a.id=selected.id where a.grupo_id=g.id)>g.maximo
    ) then raise exception 'Limite de adicionais excedido'; end if;
    v_total_item := v_base;
    for v_id,v_nome,v_preco in
      select a.id,a.nome,a.preco from public.adicionais a
      join public.grupos_adicionais g on g.id=a.grupo_id
      where a.id=any(v_ids) and a.ativo=true and g.produto_id=v_produto
    loop
      insert into public.itens_pedido_adicionais(item_pedido_id,nome,valor) values(v_item_id,v_nome,v_preco);
      v_total_item := v_total_item+v_preco;
    end loop;
    update public.itens_pedido set valor_unitario=v_total_item,total=v_total_item*quantidade where id=v_item_id;
  end loop;
  select coalesce(sum(total),0) into v_subtotal from public.itens_pedido where pedido_id=v_pedido.id;
  v_taxa_servico := coalesce(v_pedido.taxa_servico,0);
  if v_pedido.tipo in ('mesa','local') then
    select * into v_cfg from public.configuracoes_operacionais where estabelecimento_id=p_estabelecimento;
    if found then
      v_taxa_servico := round(v_subtotal*coalesce(v_cfg.taxa_servico_percentual,0)/100,2);
    end if;
  end if;
  v_desconto := coalesce(v_pedido.desconto,0);
  if nullif(v_pedido.cupom_codigo,'') is not null then
    select * into v_coupon from public.cupons
    where estabelecimento_id=p_estabelecimento and upper(codigo)=upper(v_pedido.cupom_codigo)
    limit 1;
    if found then
      if v_subtotal < v_coupon.pedido_minimo then raise exception 'Pedido abaixo do mínimo do cupom'; end if;
      v_desconto := case when v_coupon.tipo='percentual'
        then round(v_subtotal*least(v_coupon.valor,100)/100,2)
        else least(v_coupon.valor,v_subtotal) end;
    end if;
  end if;
  update public.pedidos set
    subtotal=v_subtotal,
    taxa_servico=v_taxa_servico,
    desconto=v_desconto,
    desconto_cupom=v_desconto,
    total=greatest(0,v_subtotal+coalesce(v_pedido.taxa_entrega,0)+v_taxa_servico-v_desconto)
  where id=v_pedido.id;
end;
$$;
revoke all on function public.aplicar_adicionais_pedido(uuid,text,jsonb) from public,anon,authenticated;

create or replace function public.criar_pedido_publico(payload jsonb)
returns text language plpgsql security definer set search_path=public as $$
declare v_codigo text; v_est uuid;
begin
  if lower(coalesce(payload->>'tipo',''))='local' then
    raise exception 'Para consumo local, faça o pedido pelo QR Code da mesa.';
  end if;
  select id into v_est from public.estabelecimentos where slug=trim(payload->>'slug');
  if nullif(payload->>'checkout_token','') is not null then
    select codigo into v_codigo from public.pedidos
    where estabelecimento_id=v_est and checkout_token=(payload->>'checkout_token')::uuid
    limit 1;
    if v_codigo is not null then return v_codigo; end if;
  end if;
  v_codigo:=public.criar_pedido_publico_base_20261004(payload);
  perform public.aplicar_adicionais_pedido(v_est,v_codigo,payload);
  return v_codigo;
end;
$$;
revoke all on function public.criar_pedido_publico(jsonb) from public;
grant execute on function public.criar_pedido_publico(jsonb) to anon,authenticated;

-- Mantém as opções visíveis para a equipe sem expor produtos de outros estabelecimentos.
create or replace function public.carregar_operacao_garcom(p_telefone text, p_pin text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_result jsonb; v_products jsonb;
begin
  v_result:=public.carregar_operacao_garcom_base_20261004(p_telefone,p_pin);
  select coalesce(jsonb_agg(prod || jsonb_build_object('grupos_adicionais',coalesce((
    select jsonb_agg(to_jsonb(g) || jsonb_build_object('adicionais',coalesce((
      select jsonb_agg(to_jsonb(a) order by a.ordem,a.nome)
      from public.adicionais a where a.grupo_id=g.id and a.ativo=true
    ),'[]'::jsonb)))
    from public.grupos_adicionais g where g.produto_id=(prod->>'id')::uuid
  ),'[]'::jsonb))),'[]'::jsonb) into v_products
  from jsonb_array_elements(coalesce(v_result->'produtos','[]'::jsonb)) prod;
  v_result:=jsonb_set(v_result,'{produtos}',v_products,true);
  return jsonb_set(v_result,'{pedidos}',coalesce((
    select jsonb_agg(pedido-'cliente_nome'-'cliente_telefone' order by item.ordinalidade)
    from jsonb_array_elements(coalesce(v_result->'pedidos','[]'::jsonb)) with ordinality as item(pedido,ordinalidade)
    where pedido->>'tipo'='mesa'
  ),'[]'::jsonb),true);
end;
$$;
revoke all on function public.carregar_operacao_garcom(text,text) from public;
grant execute on function public.carregar_operacao_garcom(text,text) to anon,authenticated;
