alter table public.pedidos drop constraint if exists pedidos_status_check;
alter table public.pedidos
add constraint pedidos_status_check
check (status in (
'aguardando_aprovacao','novo','confirmado','preparo','pronto',
'saiu_entrega','finalizado','entregue','cancelado'
));
create index if not exists pedidos_estabelecimento_status_created_idx
on public.pedidos(estabelecimento_id,status,created_at desc);
create table if not exists public.pedido_eventos (
id bigint generated by default as identity primary key,
pedido_id bigint not null references public.pedidos(id) on delete cascade,
estabelecimento_id uuid not null references public.estabelecimentos(id) on delete cascade,
status_anterior text,
status_novo text not null,
origem text not null default 'sistema',
responsavel_id uuid,
observacao text,
created_at timestamptz not null default now()
);
create index if not exists pedido_eventos_pedido_created_idx
on public.pedido_eventos(pedido_id,created_at);
create index if not exists pedido_eventos_estabelecimento_created_idx
on public.pedido_eventos(estabelecimento_id,created_at desc);
alter table public.pedido_eventos enable row level security;
drop policy if exists pedido_eventos_owner_select on public.pedido_eventos;
create policy pedido_eventos_owner_select
on public.pedido_eventos for select to authenticated
using (
exists (
select 1 from public.estabelecimentos e
where e.id=pedido_eventos.estabelecimento_id
and e.usuario_id=auth.uid()
)
);
create table if not exists public.notificacoes_operacionais (
id uuid primary key default gen_random_uuid(),
estabelecimento_id uuid not null references public.estabelecimentos(id) on delete cascade,
pedido_id bigint references public.pedidos(id) on delete cascade,
destinatario text not null,
destinatario_id uuid references public.equipe_operacional(id) on delete cascade,
titulo text not null,
mensagem text not null,
lida boolean not null default false,
created_at timestamptz not null default now()
);
alter table public.notificacoes_operacionais add column if not exists tipo text;
alter table public.notificacoes_operacionais add column if not exists lida_em timestamptz;
alter table public.notificacoes_operacionais add column if not exists chave_deduplicacao text;
alter table public.notificacoes_operacionais drop constraint if exists notificacoes_operacionais_destinatario_check;
alter table public.notificacoes_operacionais
add constraint notificacoes_operacionais_destinatario_check
check (destinatario in ('admin','caixa','cozinha','garcom','entregador'));
create index if not exists notificacoes_operacionais_destino_idx
on public.notificacoes_operacionais(estabelecimento_id,destinatario,lida,created_at desc);
create unique index if not exists notificacoes_operacionais_chave_unique
on public.notificacoes_operacionais(chave_deduplicacao)
where chave_deduplicacao is not null;
alter table public.notificacoes_operacionais enable row level security;
drop policy if exists notificacoes_operacionais_owner_select on public.notificacoes_operacionais;
create policy notificacoes_operacionais_owner_select
on public.notificacoes_operacionais for select to authenticated
using (
exists (
select 1 from public.estabelecimentos e
where e.id=notificacoes_operacionais.estabelecimento_id
and e.usuario_id=auth.uid()
)
);
drop policy if exists notificacoes_operacionais_owner_update on public.notificacoes_operacionais;
create policy notificacoes_operacionais_owner_update
on public.notificacoes_operacionais for update to authenticated
using (
exists (
select 1 from public.estabelecimentos e
where e.id=notificacoes_operacionais.estabelecimento_id
and e.usuario_id=auth.uid()
)
)
with check (
exists (
select 1 from public.estabelecimentos e
where e.id=notificacoes_operacionais.estabelecimento_id
and e.usuario_id=auth.uid()
)
);
create or replace function public.fsdelivery_origem_operacao()
returns text
language sql
stable
set search_path='public'
as $$
select coalesce(nullif(current_setting('fsdelivery.origem',true),''),'sistema');
$$;
create or replace function public.fsdelivery_responsavel_operacao()
returns uuid
language plpgsql
stable
set search_path='public'
as $$
declare v text;
begin
v:=nullif(current_setting('fsdelivery.responsavel_id',true),'');
if v is null then return auth.uid(); end if;
return v::uuid;
exception when others then
return auth.uid();
end;
$$;
create or replace function public.atualizar_timestamp_pedido()
returns trigger
language plpgsql
set search_path='public'
as $$
begin
new.atualizado_em:=now();
return new;
end;
$$;
drop trigger if exists trg_atualizar_timestamp_pedido on public.pedidos;
create trigger trg_atualizar_timestamp_pedido
before update on public.pedidos
for each row execute function public.atualizar_timestamp_pedido();
create or replace function public.registrar_evento_operacional_pedido()
returns trigger
language plpgsql
security definer
set search_path='public'
as $$
declare
v_origem text:=public.fsdelivery_origem_operacao();
v_responsavel uuid:=public.fsdelivery_responsavel_operacao();
v_destino text;
v_titulo text;
v_mensagem text;
v_codigo text;
begin
if tg_op='UPDATE' and old.status is not distinct from new.status then
return new;
end if;
v_codigo:=coalesce(new.codigo,new.id::text);
insert into public.pedido_eventos(
pedido_id,estabelecimento_id,status_anterior,status_novo,origem,responsavel_id
) values (
new.id,new.estabelecimento_id,
case when tg_op='INSERT' then null else old.status end,
new.status,v_origem,v_responsavel
);
if new.status='aguardando_aprovacao' then
v_destino:='caixa';
v_titulo:='Pedido aguardando aprovação';
v_mensagem:='Pedido #'||v_codigo||' precisa ser aprovado antes do preparo.';
elsif new.status in ('confirmado','novo') then
v_destino:='cozinha';
v_titulo:='Novo pedido na cozinha';
v_mensagem:='Pedido #'||v_codigo||' foi liberado para produção.';
elsif new.status='pronto' then
if new.tipo in ('mesa','local') then
v_destino:='garcom';
v_titulo:='Pedido pronto para servir';
v_mensagem:='Pedido #'||v_codigo||' está pronto para levar à mesa.';
elsif new.tipo='entrega' then
v_destino:='entregador';
v_titulo:='Pedido pronto para entrega';
v_mensagem:='Pedido #'||v_codigo||' está liberado para iniciar a entrega.';
else
v_destino:='caixa';
v_titulo:='Pedido pronto para retirada';
v_mensagem:='Pedido #'||v_codigo||' está pronto para retirada.';
end if;
elsif new.status='saiu_entrega' then
v_destino:='admin';
v_titulo:='Entrega iniciada';
v_mensagem:='Pedido #'||v_codigo||' saiu para entrega.';
elsif new.status in ('finalizado','entregue') then
v_destino:='admin';
v_titulo:='Pedido finalizado';
v_mensagem:='Pedido #'||v_codigo||' foi concluído.';
elsif new.status='cancelado' then
v_destino:='admin';
v_titulo:='Pedido cancelado';
v_mensagem:='Pedido #'||v_codigo||' foi cancelado.';
end if;
if v_destino is not null then
insert into public.notificacoes_operacionais(
estabelecimento_id,pedido_id,destinatario,tipo,titulo,mensagem,chave_deduplicacao
) values (
new.estabelecimento_id,new.id,v_destino,new.status,v_titulo,v_mensagem,
concat(new.id,':',new.status,':',v_destino)
) on conflict do nothing;
end if;
return new;
end;
$$;
drop trigger if exists trg_registrar_evento_operacional_pedido on public.pedidos;
create trigger trg_registrar_evento_operacional_pedido
after insert or update of status on public.pedidos
for each row execute function public.registrar_evento_operacional_pedido();
create or replace function public.definir_status_inicial_pedido()
returns trigger
language plpgsql
security definer
set search_path='public'
as $$
declare v_exige boolean:=false;
begin
select coalesce(c.exige_abertura_caixa,false)
into v_exige
from public.configuracoes_operacionais c
where c.estabelecimento_id=new.estabelecimento_id;
new.status:=case when coalesce(v_exige,false)
then 'aguardando_aprovacao'
else 'confirmado'
end;
return new;
end;
$$;
create or replace function public.aprovar_pedido_caixa(p_pedido_id bigint)
returns public.pedidos
language plpgsql
security definer
set search_path='public'
as $$
declare v_pedido public.pedidos%rowtype;
begin
if auth.uid() is null then raise exception 'Usuário não autenticado'; end if;
perform set_config('fsdelivery.origem','caixa',true);
perform set_config('fsdelivery.responsavel_id',auth.uid()::text,true);
update public.pedidos p
set status='confirmado'
where p.id=p_pedido_id
and p.status='aguardando_aprovacao'
and exists (
select 1 from public.estabelecimentos e
where e.id=p.estabelecimento_id and e.usuario_id=auth.uid()
)
returning p.* into v_pedido;
if not found then
raise exception 'Pedido não encontrado, já aprovado ou sem permissão';
end if;
return v_pedido;
end;
$$;
drop function if exists public.atualizar_status_pedido_operacional(text,bigint);
create function public.atualizar_status_pedido_operacional(
p_novo_status text,
p_pedido_id bigint,
p_origem text default 'admin'
)
returns public.pedidos
language plpgsql
security definer
set search_path='public'
as $$
declare
v_pedido public.pedidos%rowtype;
v_usuario uuid:=auth.uid();
v_status text:=case when p_novo_status='entregue' then 'finalizado' else p_novo_status end;
v_origem text:=case when p_origem in ('admin','caixa','cozinha') then p_origem else 'admin' end;
begin
if v_usuario is null then raise exception 'Usuário não autenticado'; end if;
if v_status not in ('confirmado','preparo','pronto','saiu_entrega','finalizado','cancelado') then
raise exception 'Status inválido';
end if;
select p.* into v_pedido
from public.pedidos p
join public.estabelecimentos e on e.id=p.estabelecimento_id
where p.id=p_pedido_id and e.usuario_id=v_usuario
for update;
if not found then raise exception 'Pedido não encontrado ou sem permissão'; end if;
if not (
(v_pedido.status='aguardando_aprovacao' and v_status='confirmado') or
(v_pedido.status in ('novo','confirmado') and v_status='preparo') or
(v_pedido.status='preparo' and v_status='pronto') or
(v_pedido.status='pronto' and v_pedido.tipo in ('mesa','local','retirada') and v_status='finalizado') or
(v_pedido.status='pronto' and v_pedido.tipo='entrega' and v_status='saiu_entrega') or
(v_pedido.status='saiu_entrega' and v_pedido.tipo='entrega' and v_status='finalizado') or
(v_pedido.status not in ('finalizado','entregue','cancelado') and v_status='cancelado')
) then
raise exception 'Transição de status inválida: % → %',v_pedido.status,v_status;
end if;
perform set_config('fsdelivery.origem',v_origem,true);
perform set_config('fsdelivery.responsavel_id',v_usuario::text,true);
update public.pedidos set status=v_status where id=p_pedido_id returning * into v_pedido;
return v_pedido;
end;
$$;
grant execute on function public.atualizar_status_pedido_operacional(text,bigint,text) to authenticated;
create or replace function public.carregar_operacao_garcom(p_telefone text,p_pin text)
returns jsonb
language plpgsql
security definer
set search_path='public'
as $$
declare
v_m public.equipe_operacional%rowtype;
v_est public.estabelecimentos%rowtype;
v_count integer;
begin
select count(*) into v_count
from public.equipe_operacional m
where regexp_replace(m.telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and m.pin=p_pin and m.funcao='garcom' and m.ativo=true;
if v_count<>1 then raise exception 'Acesso do garçom inválido ou ambíguo'; end if;
select * into v_m
from public.equipe_operacional m
where regexp_replace(m.telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and m.pin=p_pin and m.funcao='garcom' and m.ativo=true
limit 1;
select * into v_est from public.estabelecimentos where id=v_m.estabelecimento_id;
return jsonb_build_object(
'estabelecimento',jsonb_build_object(
'id',v_est.id,'nome',v_est.nome,'slug',v_est.slug,'aberto',v_est.aberto,
'taxa_entrega',v_est.taxa_entrega,'pedido_minimo',v_est.pedido_minimo
),
'produtos',coalesce((
select jsonb_agg(jsonb_build_object(
'id',p.id,'nome',p.nome,'descricao',p.descricao,'preco',p.preco,
'categoria',coalesce(c.nome,'Sem categoria'),'imagem_url',p.imagem_url,'destaque',p.destaque
) order by coalesce(c.ordem,999),p.nome)
from public.produtos p left join public.categorias c on c.id=p.categoria_id
where p.estabelecimento_id=v_est.id and p.ativo=true
),'[]'::jsonb),
'mesas',coalesce((
select jsonb_agg(jsonb_build_object(
'id',m.id,'numero',m.numero,'nome',m.nome,'token',m.codigo_qr
) order by m.numero)
from public.mesas m where m.estabelecimento_id=v_est.id and m.ativo=true
),'[]'::jsonb),
'pedidos',coalesce((
select jsonb_agg(x.obj order by x.created_at desc)
from (
select p.created_at,jsonb_build_object(
'id',p.id,'codigo',p.codigo,'numero',p.numero,'status',p.status,'tipo',p.tipo,
'total',p.total,'created_at',p.created_at,'mesa_id',p.mesa_id,
'cliente_nome',c.nome,'cliente_telefone',c.telefone,
'mesa_nome',m.nome,'mesa_numero',m.numero,
'itens',coalesce((
select jsonb_agg(jsonb_build_object(
'quantidade',i.quantidade,'nome',i.nome_produto,'nome_produto',i.nome_produto,
'observacoes',i.observacoes,'total',i.total
) order by i.id)
from public.itens_pedido i where i.pedido_id=p.id
),'[]'::jsonb)
) obj
from public.pedidos p
left join public.clientes c on c.id=p.cliente_id
left join public.mesas m on m.id=p.mesa_id
where p.estabelecimento_id=v_est.id
order by p.created_at desc limit 150
) x
),'[]'::jsonb)
);
end;
$$;
grant execute on function public.carregar_operacao_garcom(text,text) to anon,authenticated;
create or replace function public.criar_pedido_equipe_garcom(
p_telefone text,p_pin text,payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path='public'
as $$
declare
v_m public.equipe_operacional%rowtype;
v_est public.estabelecimentos%rowtype;
v_payload jsonb:=coalesce(payload,'{}'::jsonb);
v_token text;
begin
select * into v_m
from public.equipe_operacional m
where regexp_replace(m.telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and m.pin=p_pin and m.funcao='garcom' and m.ativo=true
limit 1;
if not found then raise exception 'Acesso do garçom inválido'; end if;
select * into v_est from public.estabelecimentos where id=v_m.estabelecimento_id;
v_payload:=v_payload||jsonb_build_object('slug',v_est.slug);
if coalesce(v_payload->>'tipo','')='mesa' then
select codigo_qr into v_token
from public.mesas
where id=nullif(v_payload->>'mesa_id','')::uuid
and estabelecimento_id=v_est.id and ativo=true;
if v_token is null then raise exception 'Mesa inválida ou indisponível'; end if;
v_payload:=v_payload||jsonb_build_object('mesa_token',v_token);
end if;
perform set_config('fsdelivery.origem','garcom',true);
perform set_config('fsdelivery.responsavel_id',v_m.id::text,true);
return public.criar_pedido_publico(v_payload);
end;
$$;
grant execute on function public.criar_pedido_equipe_garcom(text,text,jsonb) to anon,authenticated;
create or replace function public.finalizar_pedido_equipe_garcom(
p_telefone text,p_pin text,p_pedido_id bigint
)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare v_m public.equipe_operacional%rowtype;
begin
select * into v_m
from public.equipe_operacional m
where regexp_replace(m.telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and m.pin=p_pin and m.funcao='garcom' and m.ativo=true
limit 1;
if not found then raise exception 'Acesso do garçom inválido'; end if;
perform set_config('fsdelivery.origem','garcom',true);
perform set_config('fsdelivery.responsavel_id',v_m.id::text,true);
update public.pedidos
set status='finalizado'
where id=p_pedido_id
and estabelecimento_id=v_m.estabelecimento_id
and tipo in ('mesa','local')
and status='pronto';
return found;
end;
$$;
grant execute on function public.finalizar_pedido_equipe_garcom(text,text,bigint) to anon,authenticated;
create or replace function public.listar_entregas_equipe(p_slug text,p_telefone text,p_pin text)
returns table(
id bigint,codigo text,status text,total numeric,endereco_entrega jsonb,
cliente_nome text,cliente_telefone text,created_at timestamptz,
latitude double precision,longitude double precision,ordem_rota integer,
distancia_estimada_km numeric,duracao_estimada_min integer,
saiu_para_entrega_em timestamptz,entregue_em timestamptz
)
language plpgsql
security definer
set search_path='public'
as $$
declare v_m public.equipe_operacional%rowtype; v_est uuid;
begin
select e.id into v_est from public.estabelecimentos e where e.slug=p_slug;
select * into v_m from public.equipe_operacional
where estabelecimento_id=v_est
and regexp_replace(telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and pin=p_pin and ativo=true and funcao='entregador' limit 1;
if not found then raise exception 'Acesso inválido'; end if;
return query
select p.id,p.codigo,p.status,p.total,p.endereco_entrega,c.nome,c.telefone,p.created_at,
p.latitude,p.longitude,p.ordem_rota,p.distancia_estimada_km,p.duracao_estimada_min,
p.saiu_para_entrega_em,p.entregue_em
from public.pedidos p
left join public.clientes c on c.id=p.cliente_id
where p.estabelecimento_id=v_est
and p.tipo='entrega'
and (
(p.status in ('preparo','pronto') and (p.entregador_id is null or p.entregador_id=v_m.id)) or
(p.status='saiu_entrega' and p.entregador_id=v_m.id) or
(p.status in ('finalizado','entregue') and p.entregador_id=v_m.id and coalesce(p.entregue_em,p.atualizado_em)::date=current_date)
)
order by case p.status
when 'saiu_entrega' then 0 when 'pronto' then 1 when 'preparo' then 2 else 3 end,
p.ordem_rota nulls last,p.created_at;
end;
$$;
grant execute on function public.listar_entregas_equipe(text,text,text) to anon,authenticated;
create or replace function public.atualizar_entrega_equipe(
p_slug text,p_telefone text,p_pin text,p_pedido bigint,p_status text
)
returns boolean
language plpgsql
security definer
set search_path='public'
as $$
declare
v_m public.equipe_operacional%rowtype;
v_est uuid;
v_status text:=case when p_status='entregue' then 'finalizado' else p_status end;
begin
select e.id into v_est from public.estabelecimentos e where e.slug=p_slug;
select * into v_m from public.equipe_operacional
where estabelecimento_id=v_est
and regexp_replace(telefone,'\D','','g')=regexp_replace(p_telefone,'\D','','g')
and pin=p_pin and ativo=true and funcao='entregador' limit 1;
if not found then raise exception 'Acesso inválido'; end if;
if v_status not in ('saiu_entrega','finalizado') then raise exception 'Status inválido'; end if;
perform set_config('fsdelivery.origem','entregador',true);
perform set_config('fsdelivery.responsavel_id',v_m.id::text,true);
update public.pedidos
set entregador_id=v_m.id,
status=v_status,
status_entrega=case when v_status='saiu_entrega' then 'em_rota' else 'entregue' end,
saiu_para_entrega_em=case when v_status='saiu_entrega' then coalesce(saiu_para_entrega_em,now()) else saiu_para_entrega_em end,
entregue_em=case when v_status='finalizado' then now() else entregue_em end
where id=p_pedido and estabelecimento_id=v_est and tipo='entrega'
and (entregador_id is null or entregador_id=v_m.id)
and ((v_status='saiu_entrega' and status='pronto') or (v_status='finalizado' and status='saiu_entrega'));
return found;
end;
$$;
grant execute on function public.atualizar_entrega_equipe(text,text,text,bigint,text) to anon,authenticated;
insert into public.pedido_eventos(
pedido_id,estabelecimento_id,status_anterior,status_novo,origem,created_at
)
select p.id,p.estabelecimento_id,null,p.status,'migracao',p.created_at
from public.pedidos p
where not exists(select 1 from public.pedido_eventos e where e.pedido_id=p.id)
on conflict do nothing;
